spring.application.name=store-app

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:storedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Database Initialization
spring.sql.init.mode=always
spring.sql.init.schema-locations=file:../database/schema.sql
spring.sql.init.data-locations=file:../database/seed.sql

# H2 Console Configuration (for debugging)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
