spring.application.name=store-app

# H2 Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:storedb}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER:org.h2.Driver}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Database Initialization
spring.sql.init.mode=always
spring.sql.init.schema-locations=file:../database/schema.sql
spring.sql.init.data-locations=file:../database/seed.sql

# H2 Console Configuration (for debugging)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
